### ISSUE TITLE
Open a merge request

### ISSUE THREAD

**Issue by ofirbarak** [itayl13/StudiesExercises#1]
To let me comment you need to create a merge request. In real world case you are working on some branch XXX and when you finish, you ask to merge it to some branch (here its "master"). (master represents the production code base, usually someone else will take a look on your changes before merging).  
In order to do this: Pull requests > New pull request > Select the branches you wanna merge > Give a short description of what you did.

**Comment by ofirbarak** [comment]
In this case just copy the files to another temp directory  
Do "git revert" on your last commit  
Create a new branch and switch to it  
Add the files from the temp directory and commit and push.  
Then you could open a new merge request from your branch to master :)

**Comment by itayl13** [comment]
Done
